name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:          
          - os: macos-latest
            runtime-identifier: osx-x64

          - os: ubuntu-latest
            runtime-identifier: ubuntu-x64
          
          - os: windows-latest
            runtime-identifier: win10-x64
    
    env:
      working-directory: ./src/Pomodoro
      runtime-identifier: osx-x64

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Update Submodules 
      run: git submodule update --init --recursive
      
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
      
    - run: nuget restore Pomodoro.sln
      working-directory: ${{env.working-directory}}
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore --runtime ${{matrix.runtime-identifier}}
      working-directory: ${{env.working-directory}}
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal --runtime ${{matrix.runtime-identifier}}
      working-directory: ${{env.working-directory}}
